<script lang="ts">
  import { iconPaths } from './iconPaths';

  export type IconName =
    | 'add'
    | 'album'
    | 'alt_arrow_rigth'
    | 'arrow_right'
    | 'arrow_down'
    | 'bell'
    | 'blur'
    | 'book'
    | 'box'
    | 'burger'
    | 'cat'
    | 'chat'
    | 'check'
    | 'checklist'
    | 'chevron'
    | 'chevron_up'
    | 'chevron_down'
    | 'clipboard'
    | 'clock'
    | 'closed_eye'
    | 'cloud'
    | 'cloud_rain_line_duotone'
    | 'cloud_snowfall_minimalistic_line_duotone'
    | 'cloud_sun_2_line_duotone'
    | 'cloud_sun_line_duotone'
    | 'code'
    | 'code_funky'
    | 'code_scan'
    | 'cog'
    | 'comfetti'
    | 'compass_big_line_duotone'
    | 'copy'
    | 'copy_1'
    | 'cross'
    | 'cross_circle'
    | 'cursor'
    | 'date'
    | 'discord'
    | 'documents'
    | 'dots'
    | 'dots2'
    | 'double_arrow_right'
    | 'double_check'
    | 'download'
    | 'download2'
    | 'eraser'
    | 'extensions'
    | 'eye_closed_line_duotone'
    | 'eye_line_duotone'
    | 'file_code'
    | 'file_download'
    | 'file_text'
    | 'filter'
    | 'fog_line_duotone'
    | 'folder_search'
    | 'gallery'
    | 'ghost'
    | 'globe'
    | 'graph'
    | 'hamburger_menu_line_duotone'
    | 'headphones'
    | 'headphones_round_line_duotone'
    | 'heart'
    | 'history'
    | 'home_wifi_angle_line_duotone'
    | 'hourglass'
    | 'image'
    | 'info'
    | 'info2'
    | 'keyboard'
    | 'link'
    | 'link2'
    | 'lock'
    | 'menu_dots_circle_line_duotone'
    | 'mouse'
    | 'move_to_folder'
    | 'music'
    | 'package'
    | 'pan'
    | 'pause'
    | 'pen_new'
    | 'pen_new2'
    | 'pie'
    | 'pie2'
    | 'play'
    | 'playlist'
    | 'question'
    | 'ranking'
    | 'remove_folder'
    | 'restart'
    | 'run'
    | 'save'
    | 'select_folder'
    | 'server'
    | 'sort'
    | 'sort_down'
    | 'sort_up'
    | 'sort_vertical'
    | 'sound'
    | 'spinner'
    | 'square_circle'
    | 'star'
    | 'star_and_mini'
    | 'starry'
    | 'stats'
    | 'stop'
    | 'telegram'
    | 'text'
    | 'three_squares'
    | 'trash'
    | 'tuning'
    | 'tuning2'
    | 'undo'
    | 'user'
    | 'video'
    | 'video_replace'
    | 'video2'
    | 'warning'
    | 'weight'
    | 'widget'
    | 'widget2'
    | 'widgets'
    | 'xtwitter'
    | 'folder'
    | 'search'
    | 'maximize'
    | 'minimize'
    | 'close'
    | 'queue'
    | 'settings'
    | 'logs'
    | 'github'
    | 'platform_youtube'
    | 'platform_youtube_music'
    | 'platform_bilibili'
    | 'platform_tiktok'
    | 'platform_twitter'
    | 'platform_instagram'
    | 'platform_twitch'
    | 'platform_vimeo'
    | 'platform_facebook'
    | 'platform_weibo'
    | 'platform_generic'
    | 'arrow_outward'
    | 'refresh'
    | 'monitor'
    | 'minimize_square'
    | 'ruler';

  interface Props {
    name: IconName;
    size?: number;
    class?: string;
  }

  let { name, size = 24, class: className = '' }: Props = $props();
</script>

<svg
  width={size}
  height={size}
  viewBox="0 0 24 24"
  class={className}
  fill="none"
  aria-hidden="true"
>
  {@html iconPaths[name] || ''}
</svg>

<style>
  svg {
    color: inherit;
    flex-shrink: 0;
  }
</style>
